### ISSUE TITLE
Responsive mode is broken

### ISSUE THREAD

**Issue by oneillal** [oneillal/nci-web-project#2]
Design does not flow when viewed on mobile. Marketing rowcells are bleeding off the page. They should drop into a single column mode. This was working in previous build.

**Comment by oneillal** [comment]
@jonases Can you look at this???

**Comment by jonases** [comment]
@oneillal It's something to do with Skeleton. Remember we talked about removing that and just coding our own media queries instead.

**Comment by oneillal** [comment]
@jonases Right. Will try and get to that tomorrow. We are cutting it fine! :zap:

**Comment by oneillal** [comment]
@jonases @hanlonmk1 Tried fixing this...the problem is the JS for displaying the responsive menu...driving me :nut_and_bolt: :nut_and_bolt: Lets abandon the existing menu and use a much easier approach. See #9 :eyes:
