### ISSUE TITLE
When the navbar is docked at the top it gets a bit buggy when scrolling down

### ISSUE THREAD

**Issue by jonases** [oneillal/nci-web-project#3]
when the navbar is docked at the top(when scrolling down), the navbar is positioned on top of the banner(part of the banner is covered by the navbar).

**Comment by oneillal** [comment]
@jonases Yeah I noticed that. Try adding a div before the navbar to add a empty space with the same height. The banner would not be covered. Bit of a band-aid but we a re running out of time!

**Comment by jonases** [comment]
nice idea @oneillal! Here's the result, works perfectly :)

Before:
![before](https://cloud.githubusercontent.com/assets/7204895/25228520/a12686b6-25c4-11e7-9cce-d0536ee5aedb.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/7204895/25228521/a129f940-25c4-11e7-8045-82f0b153da8b.jpg)

**Comment by oneillal** [comment]
@jonases :+1:
