### ISSUE TITLE
Need a javacript to toggle the audio

### ISSUE THREAD

**Issue by oneillal** [oneillal/nci-web-project#4]
The audio is cool but we should throw in an a little javascript to toggle the audio on and off? @hanlonmk1 what do you think?

**Comment by oneillal** [comment]
Check out this link...
https://sankartypo3.wordpress.com/2012/11/17/javascriptjquery-to-control-html5-audio-elements/

**Comment by oneillal** [comment]
```
document.getElementById('bg_audio').muted = true;
```

**Comment by hanlonmk1** [comment]
@oneillal We probably do need something as the audio on liftoff page load is a bit loud :-)
But I'm not sure how it works if the user has control, I think it's designed to be a surprise..
Anyway we can consider how to go about it tonight. Thanks

**Comment by oneillal** [comment]
Closing this. Audio taken out when link clicked.
