### ISSUE TITLE
Javascript error with new Countdown Timer

### ISSUE THREAD

**Issue by hanlonmk1** [oneillal/nci-web-project#5]
@oneillal I have developed a Countdown timer using this good example http://codepen.io/SitePoint/pen/MwNPVq but when I tried the code it's not working. See js error below.

![](https://raw.githubusercontent.com/oneillal/nci-web-project/master/docs/Screenshot_countdown.png)

Lets talk about this later.
Mark

**Comment by oneillal** [comment]
:ok_hand:

**Comment by oneillal** [comment]
Didn't get time for this unfortunately :mask:
