### ISSUE TITLE
Document 3rd Party Resources

### ISSUE THREAD

**Issue by oneillal** [oneillal/nci-web-project#8]
-jquery
-normalize (Probably we can do without this IMO)
-skeleton (We are just using the javascript for our responsive menu)
-util.js

**Comment by hanlonmk1** [comment]
Also documenting images & video references

**Comment by hanlonmk1** [comment]
Images & video references are done and documented in 3rd_PARTY_REFERENCES.md

**Comment by hanlonmk1** [comment]
All done including CSS/JS
